apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      # version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      interval: 12h
  values:
    WEAVE_GITOPS_FEATURE_TELEMETRY: "true"
    adminUser:
      create: true
      passwordHash: $2y$05$S2Ggrl.0EcsY9wpmo8KTcenf.2J0Q8z/os6GmSb7mWyMAD6GtMave #admin
      username: admin
    ingress:
      enabled: true
      className: "nginx"
      hosts:
      - host: gitops.lan
        paths:
          - path: /
            pathType: ImplementationSpecific
