apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  interval: 24h
  url: https://weaveworks.github.io/weave-gitops
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      interval: 12h
  values:
    ingress:
      enabled: true
      className: "nginx"
      hosts:
      - host: gitops.lan
        paths:
          - path: /
            pathType: ImplementationSpecific
